### ISSUE TITLE
Project checklist

### ISSUE THREAD

**Issue by ThiagoA20** [ThiagoA20/healthcare_app#1]
- [ ] Frontend:
  - [ ] Brand
  - [ ] Home, Login, About pages
  - [ ] Responsive Design

- [ ] Backend:
  - [ ] Create database models
  - [ ] POST, GET requests
  - [ ] Make predictions

- [ ] Video:
  - [ ] Script
  - [ ] Search for videos in free video banks
  - [ ] Record the running software
  - [ ] To edit
